### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Gast9ra/JavaProject-1-task-9_option#1]
1. Приведите названия классов в соответсвие с Java Code Style и смыслом представляемых ими объектов.
2. Публичное поле `masProduct` нарушает инкапсуляцию
3. Должен ли класс `listProduct` быть вложенным? Почему бы его не сделать полноценным публичным классом и не использовать в интерфейсе прейскуранта?
4. Индекс товара в списке вообще не должен фигурировать в параметрах ваших методов.
5. Исключения -- правильный способ сообщить программисту-пользователю класса об ошибке. Зачем вы их ловите и заменяете в лучшем случае на специальное возвращаемое значение?

**Comment by Gast9ra** [comment]
исправлено

**Comment by gagarski** [comment]
1. Сделайте класс `ObjListProduct` полноценным классом: с конструктором и геттерами/сеттерами. придумайте ему нормальное название (что он представляет в вашей программе).
2. Методы типа `searchPriceByCode` не нужны, достаточно сделать метод, возвращающий `ObjListProduct`, из которого можно будет получать цену, название и т. п.
3. Сделайте так, чтобы метод добавления продукта кидал исключение при добавлении некорректного продукта. (если продукт уже существует, можно просто вернуть `false` - это довольно стандартное решение для коллекций). Возможно следует перенести эти проверки в конструктор класса `ObjListProduct`
4. Тестами покрыта явно не вся функциональность. После удаления, например, следует проверять, что продукт больше не содержится в списке, а не только возвращаемое значение `delete`
5. Подумайте, есть ли структура данных удобная для поиска по коду более, чем `ArrayList` (hint: изменения кода продукта в задании нет, можно сделать его неизменяемым)
6. У вас не реализован метод, определяющий цену покупки по коду и количеству экземпляров(см. задание).

**Comment by Gast9ra** [comment]
Отправил исправление.
